### PR TITLE
Make docker hub requests authenticated

### LINKED ISSUE #30758: `sourcegraph/update-docker-tags` should make authenticated requests to docker hub apis
```
Error: Command failed with exit code 1: bash -c set -ex

                tools/update-docker-tags.sh 3.36.3;
    at makeError (/Users/michael/Code/sourcegraph/sourcegraph/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/michael/Code/sourcegraph/sourcegraph/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at createBranchWithChanges (/Users/michael/Code/sourcegraph/sourcegraph/dev/release/src/github.ts:571:17)
    at createChangesets (/Users/michael/Code/sourcegraph/sourcegraph/dev/release/src/github.ts:463:9)
    at Object.run (/Users/michael/Code/sourcegraph/sourcegraph/dev/release/src/release.ts:373:36)
    at /Users/michael/Code/sourcegraph/sourcegraph/dev/release/src/release.ts:65:21
    at async Promise.all (index 0)
    at runStep (/Users/michael/Code/sourcegraph/sourcegraph/dev/release/src/release.ts:60:5)
    at main (/Users/michael/Code/sourcegraph/sourcegraph/dev/release/src/main.ts:18:5) {
  shortMessage: 'Command failed with exit code 1: bash -c set -ex\n' +
    '\n' +
    '                tools/update-docker-tags.sh 3.36.3;',
  command: 'bash -c set -ex\n\n                tools/update-docker-tags.sh 3.36.3;',
```

this should make authenticated request to avoid getting rate-limited https://github.com/sourcegraph/update-docker-tags/blob/master/update-docker-tags.go#L236

### PR DESCRIPTION
**Pull request by michaellzc**
Fix https://github.com/sourcegraph/sourcegraph/issues/30758

workaround for the docker hub rate limit

The solution is pretty straight forward, just add a basic auth header when invoking `auth.docker.io`. When an authenticated token is used for subsequent requests, there shouldn't be any `ratelimit-*` headers from the response

not authenticated
```
HTTP/1.1 200 OK
content-length: 2782
content-type: application/vnd.docker.distribution.manifest.v1+prettyjws
docker-content-digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
docker-distribution-api-version: registry/2.0
etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
date: Mon, 07 Feb 2022 21:56:51 GMT
strict-transport-security: max-age=31536000
ratelimit-limit: 100;w=21600
ratelimit-remaining: 100;w=21600
docker-ratelimit-source: 50.92.13.38
```

authenticated

```
HTTP/1.1 200 OK
content-length: 2782
content-type: application/vnd.docker.distribution.manifest.v1+prettyjws
docker-content-digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
docker-distribution-api-version: registry/2.0
etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
date: Mon, 07 Feb 2022 21:57:35 GMT
strict-transport-security: max-age=31536000
docker-ratelimit-source: 3c5a9d6a-3ec6-4466-9e13-b112828125d3
```

### CODE REVIEW

**Review by kevinwojo — APPROVED** [review]

**Review by caugustus-sourcegraph — APPROVED** [review]

**Review by bobheadxi — COMMENTED** [review]
Can we use access tokens https://docs.docker.com/docker-hub/access-tokens/ instead of username/passwords?

**Comment by michaellzc** [comment]
> Can we use access tokens [docs.docker.com/docker-hub/access-tokens](https://docs.docker.com/docker-hub/access-tokens/) instead of username/passwords?

password = personal access token

I'll update the CLI flag to explicitly mention both password and access token will work

**Comment by bobheadxi** [comment]
Ah yes confused myself there, LGTM

File: update-docker-tags.go [hunk 1]
```diff
@@ -79,6 +87,9 @@ Examples:
 	if err != nil {
 		log.Fatalf("failed to parse raw enforce, err: %s", err)
 	}
+	if dockerUsername == "" && dockerPassword == "" {
```
Comment (bobheadxi) [inline update-docker-tags.go:90]:
```suggestion
	if dockerUsername == "" || dockerPassword == "" {
```

It won't work with just one of the two right?

Comment (michaellzc) [reply update-docker-tags.go:90]: How about

https://github.com/sourcegraph/update-docker-tags/pull/3/files#diff-0c8db2e64ca607b73b274b4bbdff0aebe6d9dcd7c7cb4728de1dda381c9593ccR90-R95

**Review by bobheadxi — APPROVED** [review]
